name: 'datadotworld/upload-files'
description: 'Uploads files to data.world'
inputs:
  token:
    description: 'data.world API token'
    required: true
  agentdatasetid:
    description: 'data.world dataset id'
    required: true
  file:
    description: 'file to upload'
    required: true
  filename:
    description: 'filename to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.agentdatasetid }}
    - ${{ inputs.file }}
    - ${{ inputs.filename }}
